### ISSUE TITLE
Define AR relationships on Person and other objects for deletion

### ISSUE THREAD

**Issue by rabble** [affinityworks/main#102]
From the console, we should be able to delete a user and it's associated objects, like joiner tables. It shouldn't delete model objects other models need. This doesn't work currently because of database constraints and AR relationships don't define what should be deleted.

**Comment by Matt-Holland** [comment]
I can't test this because I don't have enough information about the schema.

**Comment by aguestuser** [comment]
would be nice to see what commits accomplished the above to give some hints as to which associated objects should be destroyed when a parent object is destroyed. i we knew that we could pull up a console, delete a parent, and see if the correct children were deleted.
