### ISSUE TITLE
automate dev env install [2]

### ISSUE THREAD

**Issue by aguestuser** [affinityworks/main#469]
## Acceptance Criteria

* new contributor may use either of two one-liners to install and run affinityworks:
  *  `./bin/install && ./bin/run`
  * `docker-compose up`

**Comment by Matt-Holland** [comment]
attempted to test with Docker on my local machine (Macbook, El Capitan). Seemed to run properly, but site was not available at localhost:3000
Will test again later with fresh reboot, and potentially with a different machine.

**Comment by Matt-Holland** [comment]
Ran again after fresh reboot, same result (site not available). 
In case it's useful, here is the result of `container inspect`:

 $ docker container inspect advocacycommons_web_1
[
    {
        "Id": "eed249268a1dd42747be5065b09c24b9d51f59aafd2fe301e14806a7e4154e13",
        "Created": "2018-01-22T17:18:11.899647517Z",
        "Path": "./bin/run-web",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 2491,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2018-01-23T19:16:13.521525321Z",
            "FinishedAt": "2018-01-23T19:15:35.234960129Z"
        },
        "Image": "sha256:1458eccd532542deb91bd9bf57cd7f4fe4829bf5cb24c98aba34a9f3a9796d39",
        "ResolvConfPath": "/var/lib/docker/containers/eed249268a1dd42747be5065b09c24b9d51f59aafd2fe301e14806a7e4154e13/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/eed249268a1dd42747be5065b09c24b9d51f59aafd2fe301e14806a7e4154e13/hostname",
        "HostsPath": "/var/lib/docker/containers/eed249268a1dd42747be5065b09c24b9d51f59aafd2fe301e14806a7e4154e13/hosts",
        "LogPath": "/var/lib/docker/containers/eed249268a1dd42747be5065b09c24b9d51f59aafd2fe301e14806a7e4154e13/eed249268a1dd42747be5065b09c24b9d51f59aafd2fe301e14806a7e4154e13-json.log",
        "Name": "/advocacycommons_web_1",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": [
                "/Users/mholland/Documents/_Projects/Affinity/code/advocacycommons:/affinity:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "host",
            "PortBindings": {
                "3000/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "3000"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/6603b410582111607c975cb5fe3401c7cce4f8b9c4d7a203ebec0bf03bbefd7b-init/diff:/var/lib/docker/overlay2/0a8d236258d914992f6337909966bfcb7f678c14d5c64c3c15df86afd9f9d36c/diff:/var/lib/docker/overlay2/e74ba01eeab303cd7912a905aeacb00d5db177bd6d2be69a1146210a698c3edc/diff:/var/lib/docker/overlay2/f88de614e5a3c56b16a5547e064dd8e53866a540e5e63c4e89fedd872bc68e15/diff:/var/lib/docker/overlay2/503cdf32b00e1e59f8f72ccdc2bcbac2142de3020b73d7aac1081c3a1baa6735/diff:/var/lib/docker/overlay2/fea7e050ab14189bf994e7e620fdda27329590064161e17229e4e66d6ae59594/diff:/var/lib/docker/overlay2/4f1e2e033a33a05d7c1212b94855d9f672804557a1b26add2efd1705a63cfce2/diff:/var/lib/docker/overlay2/6d503a4a8409a6dfd5c52812589979543e344a66214c11877a5c180e06811a7d/diff:/var/lib/docker/overlay2/1deb2db39dc7b6acfe5f1786e82c56e44c03e5d2bea6ebb23a0a2d2444a0960a/diff:/var/lib/docker/overlay2/a4f11a9a2da4a40f5b14528556b9ea452e85082be92749244649720fc5d35725/diff:/var/lib/docker/overlay2/601fe3730c892dbeed0956aa274015434484e10d3480a6db154483ebd0380d3f/diff:/var/lib/docker/overlay2/247837ba4bb8ffe09ad8ab341f5113365b75f869d87f0be6c447bd9d2286d8ac/diff:/var/lib/docker/overlay2/593f0693059cda8c3bff1170f4a892b4eda4e93f66514f0e77ff4bcf2a50b2a9/diff:/var/lib/docker/overlay2/5e25af4ee4c0ebcd36453cedb9a65b838c33b8844169010cc65cbcf2ed257e96/diff:/var/lib/docker/overlay2/06bc88f55766728b7df294e9e20f7f56c80d555cdf8751b42d97b44ab99ca07e/diff:/var/lib/docker/overlay2/b257d1058d9602a9087bebd7bd35e89f8a68e729ed937e108131822789e46e6d/diff:/var/lib/docker/overlay2/69af7c57100fee24e0e2a0278b5a7444b61ae1bd690255696fb372017ff03c54/diff:/var/lib/docker/overlay2/3aa4edb4037e584788695f871c4e803607387f58ffdcb5ae3d43b47c14766d47/diff:/var/lib/docker/overlay2/e48c6481af238e795f47c1d78dd77b70a8d4a5f4d79e25ba0a138aa5a05e983e/diff:/var/lib/docker/overlay2/7b95ed9e13b3657f1cdb4786ff1f9fe78bc76384c22f73da8aa2f46461940a34/diff:/var/lib/docker/overlay2/5b89b3d1e951bddacbdebda91aeae843deb434cb9ed84193d08b91693b7d6c2e/diff:/var/lib/docker/overlay2/e83e58709bd2f544bd80b28ac9f2bd6da4a17a0373585f538e7d2de0e7a476a5/diff:/var/lib/docker/overlay2/3c2e0bd4e8de125eed133a76bf7bb3437c39d4f2ecb2c5e96d294835f0afac26/diff:/var/lib/docker/overlay2/287c5b765edc1559dabfbae1afd988cdf41eaf3304d2a2107dfa65d8020f7c36/diff",
                "MergedDir": "/var/lib/docker/overlay2/6603b410582111607c975cb5fe3401c7cce4f8b9c4d7a203ebec0bf03bbefd7b/merged",
                "UpperDir": "/var/lib/docker/overlay2/6603b410582111607c975cb5fe3401c7cce4f8b9c4d7a203ebec0bf03bbefd7b/diff",
                "WorkDir": "/var/lib/docker/overlay2/6603b410582111607c975cb5fe3401c7cce4f8b9c4d7a203ebec0bf03bbefd7b/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/mholland/Documents/_Projects/Affinity/code/advocacycommons",
                "Destination": "/affinity",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "linuxkit-025000000001",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "3000/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "AFFINITY_DEV_DB_PASSWORD=x4RIy4H.jW.^w%:;Pt",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US:en",
                "LC_ALL=en_US.UTF-8",
                "NODE_VERSION=6.9.0",
                "NVM_DIR=/.nvm",
                "RUBY_VERSION=2.3.3",
                "GEMSET_NAME=affinity"
            ],
            "Cmd": null,
            "Image": "affinityworks/web:latest",
            "Volumes": {
                "/affinity": {}
            },
            "WorkingDir": "/affinity",
            "Entrypoint": [
                "./bin/run-web"
            ],
            "OnBuild": null,
            "Labels": {
                "Description": "Base image for running affinity.works web app.",
                "com.docker.compose.config-hash": "e61978b4d7dc5706c6dd547a0f9a698276cfa83d258a501626258c51d3c41c3b",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "advocacycommons",
                "com.docker.compose.service": "web",
                "com.docker.compose.version": "1.18.0"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "10ccf0c53f80486dec78ff0750bd4447652ed711cfc0bde1601f85407765f033",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/default",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "host": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "33bae3877be4a7740f2046ca61c499d0b23d3477f42ed33b9b98186cee8e3314",
                    "EndpointID": "43baeeb9b766c07e5e20a2b0d3b01b0d1c1e90c588edcbfab17d000ed691b157",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by Matt-Holland** [comment]
we're going to accept this ticket as-is, and update the Readme to warn people the Docker only works on Debian. We'll come back later and see if we can get it to work on Mac also.
