### ISSUE TITLE
Public Group Signup Page [3]

### ISSUE THREAD

**Issue by Matt-Holland** [affinityworks/main#476]
Create a public signup page for a specific group, which allows people to add their names and other data to the group's database in Affinity. Also create or extend data models as needed to store the information needed to display the form.

A given form should record people into only one specific group. The use case is that an organizer for a group enters the admin interface and generates a signup form, which ties anyone who inputs their information to that specific group. For _this_ ticket, the admin interface for organizers is not required.

See details highlighted on wireframe below:

<img width="779" alt="untitled" src="https://user-images.githubusercontent.com/1071298/35311817-99f2b804-0086-11e8-929d-ca9da7ad63dc.png">

1. is the Group Name, as stored in Affinity

2. is a block of text, in html, stored for this specific form. There is currently no place in the Affinity data model to store this, it will need to be added.

3. Call-to-action text, specific to this particular form.

4. These fields may be any fields which are stored for a member in the Affinity User model (which are not intended to be automatically updated, e.g. timestamps). The form creator will be able to select which fields are displayed, and whether or not they are required. The email address field should be format-validated in the form, before submission.

5. Button text, specific to this particular form.

NOTE: This form assumes that there will also be an admin page where the group organizer can make selections to customize the form. That will be handled in a separate ticket; for this ticket, it is acceptable for Affinity staff to enter the configuration data into the database manually.

**Acceptance Criteria:**
- an Affinity staff system admin can enter values for the form text block, call to action text, included and required form fields, and button text, and generate a new signup form.
- the signup form is displayed on a public URL
- a person can visit the form at the public URL and enter their data into the form fields and click the submit button
- the form will reject an invalid email address and not allow submission (if the email field is included in the form, and regardless of whether email is a required field)
- the form will not allow submissions when a user has not filled out required fields
- upon submission, the data for the person is added to the Affinity database for the group which generated the form
- a "Success" or "Error" flash message is displayed after the data is processed.
- "Error" messages will include information about which form field generated the error. possible messages include: (1) user provided an invalid email address, (2) user did not fill out a required field -- along with the name(s) of the missing fields
- an identifier of some sort for the form is stored along with the user's data, as the "source" of the user

**Comment by aguestuser** [comment]
Few questions:

* is it important that the HTML text block specified in (2) be inputed in HTML? may it be inputed in markdown instead? (i've built tools that use markdown for this purpose and have found them simpler to use. for the sysadmin-generated phase, it also might be simpler to input)
* the spec "simple 'Success' or 'Error' message" suggests that there are no field-by-field error messages displayed if any field validations, including the specified validation for email addresses. is that correct? (eg: if i enter an invalid email address and hit enter, will i see "Error" but not indication that the error had to do with my email address being invalid?)
* i assume that the group membership data generated by completing this form should be synced back to action network. is that correct? if so (and possibly out-of-scope for requirements gathering phase, since this is an implementation detail), do you know if is it necessary to write any serialization/networking logic to make sure that this sync happens? or should it happen automatically by virtue of a new membership having been created in affinity?

**Comment by aguestuser** [comment]
thank you!

follow up question (which *definitely* bleeds into implementation details): *  if the data is not synced back, do you know off the top of your head if it is necessary to write any new logic to **stop** it from being synced back? 

as an emerging architectural question (will add to the wiki!): do we have any systematic design-pattern-driven way to distinguish what data is and is not synced (like a `Syncable` module that is always mixed in to models that should be synced, and never mixed in to ones that should not?)

**Comment by Matt-Holland** [comment]
The big-picture answer is, "we need a big-think about how to manage 'Affinity-native' data vs. 'synced with external CRM' data". Should do that pretty soon, actually.

The immediate answer here is this:
- In order for the members of a group to be synced up to ActionNetwork, the group must have an "an_api_key" stored in the Groups model. The concept here is that if you created the group in Affinity, then it _cannot_ have an Action Network api key (since it didn't originate there), and therefore no syncing can or will happen.

But, to the original point, I don't think that's a very good design pattern ("try to sync and just fail if there's no key") for the long term.

**Comment by aguestuser** [comment]
gotcha. big picture think about how we keep track of synced/non-synced data does sound useful!

also, just to make sure i understand the current state. i interpret your answer to mean that it is impossible to have the following user journey: (1) start a group for MyOrg on affinity, (2) *then* start a group for MyOrg on action network, (3) sync the two groups. ie: if i wanted to sync between the two platforms, i'd have to reverse the order of step 2 and 1?

**Comment by aguestuser** [comment]
also, i interpret it to mean that the granularity at which syncing is controled is at the *group* level, not the class level. ie: a group may *not* elect to have members synced but not events. if a group has anything synced they have everything synced. is that right?

**Comment by aguestuser** [comment]
^-- @Matt-Holland

**Comment by aguestuser** [comment]
will move above questions into slack. (increasingly off-topic for this ticket. :))

**Comment by aguestuser** [comment]
back to requirements: we said that email was the only field with validations. what about required fields (which on the backend will be a validation). 

* are any fields other than email required? 
  * if so, are the same fields always required? (ie: if i choose to include zip code in the form, will it always be a required field?)
  * if so, may a sysadmin (or later, an organizer) specify which fields are required on a case-by-case basis? (seems complicated. i'm asking to rule it out.)

**Comment by Matt-Holland** [comment]
**ANSWERS** 

- Email is _not_ always required
- no particular field is _always_ required
- the person creating the form, (sysadmin or organizer) should be able to select any field used on the form as required.

**Comment by aguestuser** [comment]
answer: 

* bits about required fields refer to an outdated version of above question (sorry!)
* we want field-level error messages in a red flash box for all validation errors (where a validation error may be (1) an invalid email address, (2) a missing required field)

**Comment by aguestuser** [comment]
> an identifier of some sort for the form is stored along with the user's data, as the "source" of the user

do we already have a way of representing what the "source" of a user is? or will these forms be the first time we track that?

**Comment by Matt-Holland** [comment]
Our data model is based on the OSDI standard, which defines a "source" field for the person object (http://opensupporter.github.io/osdi-docs/people.html#fields)  as:

source | string | Information about the source where this person record was acquired. Example: “facebook-ad-october”

**Comment by aguestuser** [comment]
cool. i should read through the OSDI spec sometime!

as per implementation strategy, i'd propose we store something like this in the `source` field of the user table after form submission: `"affinity:group_signup_form:#{id}"` (where `id` is the id of the `GroupSignupForm` model we used to make this form.)

**Comment by Matt-Holland** [comment]
The "Source" field needs to be easily readable/understandable to a "normal" organizer user, as these are commonly used in list-building queries.

**Comment by aguestuser** [comment]
estimating as a 3 (on 1,2,3,5,8 scale.) 

data model changes are straightforward. complexity comes from not having touched our front-end code yet and anticipating the particularities of storing/validating hmtl strings. also general eagerness to estimate conservatively as i find my way into the codebase and navigate unknown unknowns.

**Comment by aguestuser** [comment]
one last one: regarding whether this form always creates new accounts or not when a user fills it out.

my reading of the specs are as follows:

* we assume an anonymous (ie: not logged in) user is filling out the form, or that if a user is logged-in, we do not use that information when processing their form submission
* we assume that after filling out the form, a new `Person` record (and thus a new Affinity account) will always be created for the user (and given a `Membership` in the `Group` whose form they just filled out)
* we assume that such a new `Person` record will always be created regardless of whether Affinity already has a record of this real-world person in the database or whether they already have a `Membership` in the `Group` (ie: filling out the form might create duplicate accounts and/or duplicate group memberships for already-existing users, and we are okay with that.)

i think these are fairly straightforward readings of the specs above, but they are nevertheless **assumptions**, so i list them here to make sure i'm not off-base.

**Comment by aguestuser** [comment]
(if we *do* want to handle any dupe detection/avoidance, i'd propose we carve that out into a separate card.)

**Comment by aguestuser** [comment]
> The "Source" field needs to be easily readable/understandable to a "normal" organizer user, as these are commonly used in list-building queries.

does `affinityworks:group_signup_form:23` count as easily readable?

perhaps better is `affinityworks:group_signup_form:swing_left` would be better?

what i'm thinking about implementation-wise here is whether our system will need to use this field to determine the source of the user. if not, then i don't need to worry about it. (yay!) if so, i want to store enough information to uniquely identify this form given only the string. 

and if i'm trying to do that, i'd want the id of the form in the `source` field (or at the very least the group name in it, which i can then use to infer the id of the form). if a group can have multiple signup forms, then i would *have* to store the id to be able to retrieve the form given only the source string.

then again: if we want to be able to retrieve this form as the source of a user and we *don't* want to store uniquely identifying information about it in the `source` string, that's cool too. it just means more work, as i will have to add a new join table to track the relationship between the user and the signup form. (trying to descope that work was what motivated asking the above question about the source field.)

**Comment by aguestuser** [comment]
quick check-in. turns out "any fields which are stored for a member in the Affinity User model" was a bit more complex than i expected, since lots of the fields we would expect in a form like this are not actually on the `Person` model, but in its (many) nested children. i took my best guess at what fields we actually want, but was hoping you could double check me before moving on. (this includes all fields we use on the new member form, and some address fields that are not included in that form):

https://github.com/affinityworks/main/blob/45086254b916a54bc3d31b9a12ab9594db5671aa/app/models/group_signup_form.rb#L35-L55

**Comment by Matt-Holland** [comment]
**REVISIONS!**

This is a special case of the more general case of "creating a form".

A form shall be handled as an [OSDI "form"](https://opensupporter.github.io/osdi-docs/forms.html).

The form shall have both a "title" (the public-facing title which is shown on the form to end users) and an "administrative name" (the text string used in Affinity to display a list of forms to the organizer and admin users.) If the organizer user creating the form does not enter a "name", then we'll automatically copy the "title" into the "name" field as well.

When a person submits the form, we follow the OSDI spec to create a [submission record](https://opensupporter.github.io/osdi-docs/submissions.html)

We _won't_ assign a "source code" to the form itself. That is properly done by appending a code to the end of the form url, instead. Processing as source code appended to a form URL is out of scope for this ticket.
