### ISSUE TITLE
change ownership of Heroku pipeline

### ISSUE THREAD

**Issue by Matt-Holland** [affinityworks/main#478]
heroku
You can view your ticket and add additional comments at https://help.heroku.com/tickets/546426

Hi Matt,

I spent some time looking into this for you and have concluded we don't have any direct way for accomplishing what you are asking for. However, there is a solution whose result will essentially be the same. If you follow the instructions for upgrading a postgres database: https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases#upgrading-with-pg-copy. You'll be able to separate your staging/production databases while retaining all of the data. In short, you'd create a new database attachment to production, put both prod and staging into maintenance mode, copy the data over, and promote the new database on production. This will leave production as the billing app for the new database.

Regards,
Goose

**Comment by aguestuser** [comment]
happy to confirm that this is DONE DONE!
