### ISSUE TITLE
auto-generate a signup page for a newly-created group

### ISSUE THREAD

**Issue by Matt-Holland** [affinityworks/main#486]
**Acceptance Criteria:**
Given that I'm a person who has just created a new group using the public group creation page,
When I finish the group creation process,
Then a "join" page comes into existence where members of the public can become a member of the group.
- [ ] The join page has a url like: http://hostname/Name-Of-Group/join
- [ ] the template for the join page is based on the Swing Left design (this can be hardcoded, I do not need the ability to change this setting in this iteration of the feature).

Given that I'm the creator of the new group, 
When I add text or html to the "description" field for the group, 
either on the group creation page or on the group edit page in the admin system,
Then the text or html is displayed on the join page specific for this group.

**Comment by aguestuser** [comment]
closing as duplicative of #501
