### ISSUE TITLE
send group creation confirmation email

### ISSUE THREAD

**Issue by Matt-Holland** [affinityworks/main#487]
**Acceptance Criteria**
As a person who has just created a new group,
When I complete the group creation steps on the webpage,
Then the system will send me an email, which will include

- [ ] the URL to the admin dashboard page for my new group
- [ ] the URL for the new public "join" page for my new group
- [ ] instructions on how to modify my group and how to promote it to new people to join
- [ ] an address to which I can write for help

**Comment by aguestuser** [comment]
anything about FB login for this card?

**Comment by aguestuser** [comment]
resolved by #520
