### ISSUE TITLE
relax phone number validation [1]

### ISSUE THREAD

**Issue by aguestuser** [affinityworks/main#511]
# Acceptance Criteria

GIVEN the system is trying to save a phone number
* THEN it should fail to save if it matches the blocked criteria defined below but should save if it matches the allowed criteria below

# Definitions

## allowed phone number formats:
* [STUB]

## forbidden phone number formats:
* [STUB]

# Context

Currently we use this regex to validate phone numbers:

```ruby
/\A(\((\d){3}\)\s|(\+1-)?(\d){3}-)(\d){3}-(\d){4}|(\d){10}\z/
```

Which yields the following results:

## allowed formats:

"(123) 456-7890"
"+1-123-456-7890"
"123-456-7890"

## forbidden formats:

""
"123456-7890"
"1212sdfsd2121"
"(12)"
"this is a #%(%& garbage string 31"
"this is a garbage string 318"
"1212/1212"

# questions:

* what are some formats we know we want to allow but do not currently allow?
* eg: what about extensions?

**Comment by aguestuser** [comment]
@Matt-Holland I would like your help in fleshing out the `Definitions` section above and consider myself blocked on proceeding (due to lack of clarity around AC's) until we do that.

**Comment by Matt-Holland** [comment]
Valid number formats
        (734) 555 1212
         (734) 555.1212
         (734) 555-1212
         (734) 5551212
         (734)5551212
         734 555 1212
         734.555.1212
         734-555-1212
         7345551212
        
         Invalid:
Less than 10 digits (must have area code)
Alphabetic characters (no extensions allowed)
Any special characters not explicitly included in the allowed formats

**Comment by aguestuser** [comment]
note to self, this should work:

```ruby
/(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]?\d{3}[\s.-]?\d{4}/
```

matches:

(734) 555 1212
(734) 555.1212
(734) 555-1212
(734) 5551212
(734)5551212
734 555 1212
734.555.1212
734-555-1212
7345551212

does not match

345551212
(34) 555 1212
734-555-1212 ext 2
7345551212!
