### ISSUE TITLE
login creator of subgroup after subgroup creation [1]

### ISSUE THREAD

**Issue by aguestuser** [affinityworks/main#512]
# Acceptance Criteria

GIVEN I have just created a subgroup and been made its organizer (as per #503 )
* THEN I should be automatically logged in
* AND THEN I should be redirected to my profile page

# Questions

* should we redirect to signup page (as currently) or to dashboard (as originally specified in #503)

**Comment by Matt-Holland** [comment]
Redirect to group dashboard

**Comment by aguestuser** [comment]
note: as per convo w/ @Matt-Holland we are going to redirect to profile page not group dashboard page after login (as with other logins)
