### ISSUE TITLE
kill the "activity feed" [1]

### ISSUE THREAD

**Issue by Matt-Holland** [affinityworks/main#515]
# Acceptance Criteria

GIVEN i am a logged-in organizer of group `foo` with id `1`
* WHEN i visit my group's dashbaord (at `groups/1/dashboard`)
* THEN i should not see an activity feed

# Context

Just delete it entirely. It doesn’t work right, nobody asked for it, and it’s a security hole.

**Comment by aguestuser** [comment]
ANSWER: kill 1-4. leave only whiteboard and "edit group" as options on dashboard.

**Comment by aguestuser** [comment]
done. resolved by #525
