### ISSUE TITLE
revise subgroup signup form fields [2]

### ISSUE THREAD

**Issue by aguestuser** [affinityworks/main#521]
# Acceptance Criteria

GIVEN I am an aonymous user visiting a subgroup signup page:
* THEN: i should be **required** to enter first name, last name, email address, and *zip code*
* AND: i should **optionally** be able to enter my phone number
* AND: the call to action should read "Join the Group" (instead of "get involved")

# Notes

* there is hidden complexity in this card because we are using a custom form, and are going to have to start persisting more meta data about form fields in the db to note required/not-required

**Comment by Matt-Holland** [comment]
Looks good!
