### ISSUE TITLE
Placeholder link to Google Group on group dashboard page [1]

### ISSUE THREAD

**Issue by Matt-Holland** [affinityworks/main#533]
# Acceptance Criteria

GIVEN I am a member of a group with gsuite support:
* WHEN I visit the group dashboard page
* THEN I should see a "Coming soon -- google group" list element under the "Links" header

# Context

After we've played #532 , this can be an actual link... with something like:

https://groups.google.com/a/affinity.works/forum/#!forum/test2-mayday

Opens in a new tab

**Comment by mattewing** [comment]
What about including a placeholder with some "coming soon" language for the demo release? Showing folks that this will exist will change their perceptions of the project.

**Comment by aguestuser** [comment]
closing as not-agile and duplicative of #578
