### ISSUE TITLE
link to signup page from group dashboard [1]

### ISSUE THREAD

**Issue by aguestuser** [affinityworks/main#554]
# Acceptance Criteria

GIVEN I am visiting the dashboard page of my group (`group/1/dashboard`)
* THEN I should see a `Resources` section including a link to my group's signup form

# Implementation Note
* we could derrive this link (as `new_group_signup_form_signup`) or store it as `group.signup_form.browser_url` (which is the OSDI-compliant approach). as per discussion with @Matt-Holland , since the latter is only marginally more complex and simplifies things down the line, we will opt for that approach

**Comment by mattewing** [comment]
This feels like a key feature to ship with.

**Comment by tyesha** [comment]
@aguestuser What the sign-up page? What is the user story for this ticket?

**Comment by aguestuser** [comment]
@tyesha : sorry for lack of context!

The user story that this ties into would be roughly:

* As an organizer who wants to grow my group
* I want a public signup form 
* So that I can pass the link around to easily recruit new members
* And they can sign up for my group without having to be logged in

The user journey would be something like this:

* Alice visits affinity for the first time (not logged in) and creates a subgroup of Big Network -- call it "Ohio Chapter of Big Network"
* Alice is automatically logged in and redirected to the dashboard for her new group where she sees some helpful links. She also receives a welcome email with helpful links. One of those links is a link to the public signup page to her new group
* Alice sends the link around to her friends
* Bob sees the signup link and clicks on it
* Bob now signs up for the Ohio Chapter, and send the link around to *his* friends
* etc...

The basic functionality we have already completed is (see attached PRs for screenshots):

* a sysadmin can create a public group signup page from the console #476
* anyone may create a subgroup of a group without logging in -- #508 
* whenever someone creates a subgroup of a group, they are:
  * automatically logged in and redirected to their group dashboard -- #517 
  * sent a welcome email with helpful links, including link to the signup form -- #520

The last missing thing is to usefully display the signup page link on the dashboard when Alice logs in for the first time (or subsequent times) so she doesn't have to go digging back through her email to find it.

So, we'd like to put it on the dashboard page:

https://dev-affinityworks.herokuapp.com/groups/1/dashboard

![dashboard](https://user-images.githubusercontent.com/6032844/38155761-6f5d6fae-3447-11e8-94db-314ce942182d.png)

Which, while we're at it, could be a lot more welcoming!! :)

(see other cards in this epic about making the "Additional Description" look and feel like a "Whiteboard")

Also: the design of the group creation page and the signup pages are super-duper-bare-bones bootstrap (as noted in other cards). This seemed appropirately lean/agile at the moment, but everything should probably be a lot less bootstrap-looking eventually. :)

**Comment by aguestuser** [comment]
Hope that helped?

**Comment by Matt-Holland** [comment]
If the group has no signup page, then the "signup page" link should not be shown. I.e., _don't_ show this:

![affinity](https://user-images.githubusercontent.com/1071298/38375868-1239d1e6-38ac-11e8-9ba6-76b7514fe093.png)

**Comment by Matt-Holland** [comment]
When the group DOES have a signup form, the link is incorrect.
E.g.:
dashboard page is: http://dev.affinity.works/groups/25/dashboard
but link to signup page is: http://dev-affinityworks.herokuapp.com:3000/groups/25/signup_forms/17/signups/new

**Comment by aguestuser** [comment]
UPDATE, this is now resolved by #600 and #601 

# Notes

* organizer of a group with no resource links sees an empty list
* links are printed out
* port is no longer included in generated urls
* HOSTNAME for `dev-affinityworks` updated to `dev.affinity.works`
* provide a `Migration.backfil_signup_urls` script for one-time use to persist urls for all groups that have singup forms
* add a weedy fix to prevent signup urls created in a review app from being displayed in dev, etc..

# Screenshots

empty:

![resources-empty](https://user-images.githubusercontent.com/6032844/38381229-23db95b0-38d4-11e8-97d0-82a3974b7241.png)

non-empty:

![resources-link-good-on-dev](https://user-images.githubusercontent.com/6032844/38387341-6fa17076-38e5-11e8-9fe5-39a69fcec90b.png)

**Comment by Matt-Holland** [comment]
works!
