### ISSUE TITLE
clarify whiteboard description [1]

### ISSUE THREAD

**Issue by aguestuser** [affinityworks/main#568]
# Acceptance Criteria

WHEN i go to my group dashboard page, the editable HTML section at the top should be described as follows:
* header: "Whiteboard"
* description text: "Content for your team to see when they login"
* button text: "Edit Whiteboard"

# Context
* currently it says "Additional Description" which is confusing and uninformative:

![whiteboard-fail](https://user-images.githubusercontent.com/6032844/38203204-6bb264be-366c-11e8-911c-def8782295c5.png)

**Comment by Matt-Holland** [comment]
When the group DOES have a signup form, the link is incorrect.
E.g.:
dashboard page is: http://dev.affinity.works/groups/25/dashboard
but link to signup page is: http://dev-affinityworks.herokuapp.com:3000/groups/25/signup_forms/17/signups/new

**Comment by Matt-Holland** [comment]
![affinity](https://user-images.githubusercontent.com/1071298/38376616-d83c8c48-38ad-11e8-97d2-1797911d1d87.png)

**Comment by aguestuser** [comment]
UPDATE: fixed by #602 

screenshot:


![whiteboard-everywhere](https://user-images.githubusercontent.com/6032844/38387535-14d37666-38e6-11e8-895d-fbccf53f8485.png)

**Comment by Matt-Holland** [comment]
works!
