### ISSUE TITLE
remove double slashes from generated urls [1]

### ISSUE THREAD

**Issue by jlgoldman** [affinityworks/main#569]
# Acceptance Criteria

GIVEN i am viewing a welcome email
* THEN I should not see double slashes in the 

GIVEN I am on my dashboard
* THEN I should not see double slashes in any of the links listed in the main section

# Context

report from @jlgoldman :

> "To administer your group, login to: https://production-swingleft.herokuapp.com//profile."
> 
> The profile link appears to be broken.

**Comment by jlgoldman** [comment]
Ah sorry, the url isn't broken, it just looks broken because of the double-slash (//profile) so I assumed there was a missing path element. I see the double-slash in a lot of urls. So that's the underlying bug here and is worth fixing.

**Comment by aguestuser** [comment]
+1

i agree double slashes should go!

easy fix (changing $HOSTNAME in confgs). will add to queue for this week.

**Comment by aguestuser** [comment]
ps: do you have any other spots in app that are top-of-head where you see double slashes that would be good to spot check to verify i've closed this ticket?
