### ISSUE TITLE
user has "start" page and "account" page [2]

### ISSUE THREAD

**Issue by jlgoldman** [affinityworks/main#571]
When I click on my name in the upper right, and then choose "Account", it takes me to /profile, which shows a listing of my group and all its subgroups. That feels neither like an Account page nor a Profile page. Clicking on an avatar and then going to Account usually takes you to where you can edit your name, password, and other account settings.

The group listings page feels more like a dashboard or "home" page.

Relatedly, when you click on the Affinity logo, it takes you to the landing page, which both needs to get updated at some point and probably isn't the correct destination for a logged-in user clicking on the logo. I believe that prototypically clicking on a logo when logged into a service should take you back to the "main" or "dashboard" page, so that a user who gets lost can always go back to the most useful screen. Taking you to the landing page might just make you more lost.

**Comment by aguestuser** [comment]
thank you! i've also been wondering about redirecting "home" to the splash page. feels confusing and strictly incorrect as UX.

i'd guess that fixing this flow is not must-have for soft-launch but must-have for hard-launch. is that correct?

**Comment by aguestuser** [comment]
cc @tyesha

**Comment by tyesha** [comment]
- https://dev-affinityworks.herokuapp.com/profile  I am assuming this page is showing me all of the groups I'm a member of. This should be the user's app landing page. This is where the logo should take them when logged in. 
- Add a link to Account Details to this page. 
- Account link in drop down can go to the Account Details page now.
- Display the user's name not their role in the top right. 

I would do these things right away. It's super confusing as it is. 


We should add a footer where we can put links to other pages including the Home page. (I'll make another ticket for this.)

@aguestuser

**Comment by aguestuser** [comment]
thanks @tyesha !!

**Comment by Matt-Holland** [comment]
Note: We *also* need to create a meta "user profile" page which is about the user's details across all groups, not just in a specific group context, but that can be for later.
