### ISSUE TITLE
link to google group on group dashboard [1]

### ISSUE THREAD

**Issue by aguestuser** [affinityworks/main#578]
# Acceptance Criteria

GIVEN I am a member of a group with gsuite support:
* WHEN I visit the groups dashboard
* THEN I should see a link to the group's google group under the `Resources` heading

# Context

* dependent on #533, #532

**Comment by Matt-Holland** [comment]
can't verify this in either review app or in master.

**Comment by aguestuser** [comment]
see conversation in #532 

same context applies here. if you are looking at a group that was created before today, it will not have a `GoogleGroup` record persisted, and thus we will not have stored its url. if you look at a freshly created group, you should see a link.

i propose we *not* try to backfill right now, but am open to being overruled.

**Comment by aguestuser** [comment]
closing as resolved by #615
