### ISSUE TITLE
BUG: broken FB group-joining path for user not logged-in to FB

### ISSUE THREAD

**Issue by vaughanj10** [affinityworks/main#668]
* symptom: If a user tries to sign in (from /admin/login) using Facebook, and the user is not already signed into Facebook, then the user will hit a facebook error.

**Comment by vaughanj10** [comment]
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/1255074/39781688-ef92eb54-52dd-11e8-9e0e-41969131f847.png">

**Comment by aguestuser** [comment]
@vaughanj10 : i cannot reproduce this locally. 

when clicking either "login with facebook" on `admin/login` or "join with facebook" on `groups/1/join`, i am redirected to login to FB, as expected:

![login-to-facebook](https://user-images.githubusercontent.com/6032844/39826937-66fb782c-5384-11e8-8f99-92a1fc33e7fe.png)

**Comment by aguestuser** [comment]
(trying again on prod app)

**Comment by aguestuser** [comment]
okay... so i tried on `staging.affinity.works` and `app.affinity.works` and i cannot reproduce the bug. whenever i click "login with facebook" or "join with facebook" i am redirected to the login page. after i login, OAuth works as expected.

**Comment by aguestuser** [comment]
@vaughanj10 : am i missing something? else let's close this?
