### ISSUE TITLE
PERF: Tag queries cause runaway memory bloat

### ISSUE THREAD

**Issue by aguestuser** [affinityworks/main#700]
# Symptoms

* when I visit a members page on staging (in which many members have been tagged), it takes a members page > 10sec to load
* in a clean DB with no tags, it takes under 1 sec (reduced from 5 sec by optimizing membership queries)

# Findings from Profiling

### Summary

The problem is runaway memory bloat -- repeated requests to a members page consume memory in a "stair-step" pattern. Memory is allocated and never deallocated until either (1) we restart the dyno or (2) the program crashes (which it eventually will if member pages continue being requested.) At the point where dynos must allocate swap memory (ie: use the hard drive), performance slows markedly. The runaway memory bloat can be traced to our implementation of tagging, which requires either optimization or an outright rewrite. See below for detailed findings and a proposed course of action.

### Details

* Witness this stairstep pattern from the Heroku metrics panel (produced by fetching page 1, 2, 3, etc... of the groups/2/members route in staging):

![memory-bloat](https://user-images.githubusercontent.com/6032844/40945050-0f94a36e-6825-11e8-9bac-920eeaa93fcf.png)

* When running the Scout memory profiler we observe a similar stair-step pattern:

![requests](https://user-images.githubusercontent.com/6032844/40945064-190bb842-6825-11e8-9db1-5847ad769bab.png)

* We observe that after requesting this once, the memory never goes back down unless we restart the web dyno or the app crashes

* When investigating Scout's "memory bloat insights" tab, we see that the most costly action is a series of queries for tags:

![scout-bloat-overview](https://user-images.githubusercontent.com/6032844/40945080-2a10a85a-6825-11e8-930e-3e30fa1747ff.png)

* These queries return ~50K rows (which is interesting b/c the group in question only has 300 members):

![memory-bloat-tag-find](https://user-images.githubusercontent.com/6032844/40945089-313e3eda-6825-11e8-8892-8a9ea3d270a1.png)

* Finally, we observe that there is a setting in the `acts_as_tagable` gem to "remove unused tags" that we have not currently toggled to true. Perhaps this is why we see over 50K tags being queried and memory allocations that do not go away?

![lol](https://user-images.githubusercontent.com/6032844/40945102-3ecb1352-6825-11e8-9147-87bb90292650.png)

# Proposed course of action

* Try to reproduce memory bloat issue on local dev machine

* Investigate whether destroying unused tags mitigates memory bloat

* Look for a way to include the tag fetching in the single query for memberships that we produced in #699 (note below how it is performed separately b/c we are leaning on `acts-as-tagable`):

```ruby
    @memberships =
      Membership
        .includes(:group, :tags, :notes, person: [ :email_addresses, :personal_addresses, :phone_numbers, :groups ])
        .where(group_id: current_group.affiliates.pluck(:id).push(current_group.id))
        .order("#{sort_param} #{direction_param}")
        .page(params[:page])

    @memberships = @memberships.tagged_with(params[:tag]) if params[:tag]

```

# Resources:

* https://devcenter.heroku.com/articles/ruby-memory-use
* http://book.scoutapp.com/memory-bloat.html#what-you-need-to-know-about-memory-bloat
* https://www.engineyard.com/blog/thats-not-a-memory-leak-its-bloat
* https://www.schneems.com/2015/05/11/how-ruby-uses-memory.html

**Comment by vaughanj10** [comment]
Update:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1255074/40959718-89ddfa12-686b-11e8-8081-49ffff1712ca.png">

<img width="650" alt="image" src="https://user-images.githubusercontent.com/1255074/40959892-0884b450-686c-11e8-90c6-83f50cfb8b8f.png">

These images are from staging-affinityworks-pr-701 review app Scout metric dashboard. 

Was able to reduce allocations by 90%+ by only querying for distinct Tags in `by_type` scope. With just this one change, there are no more immediate memory quota exceeded incidents in heroku.

**Comment by vaughanj10** [comment]
It appears that the issue is with the Roar::Decorator gem when dealing with very large collections. 

``` ruby
2.3.3 :015 > Tag.type_membership.count
   (37.4ms)  SELECT COUNT(*) FROM "tags" INNER JOIN "taggings" ON "taggings"."tag_id" = "tags"."id" WHERE (taggings.taggable_type = 'Membership')
 => 36002
2.3.3 :017 > Benchmark.measure { JsonApi::TagsRepresenter.for_collection.new(Tag.type_membership).to_json }
  Tag Load (147.1ms)  SELECT "tags".* FROM "tags" INNER JOIN "taggings" ON "taggings"."tag_id" = "tags"."id" WHERE (taggings.taggable_type = 'Membership')
 => #<Benchmark::Tms:0x007fa431381328 @label="", @real=7.654750999994576, @cstime=0.0, @cutime=0.0, @stime=0.8699999999999974, @utime=6.0, @total=6.869999999999997>
```

As seen here, the querying for 42000 tags is relatively fast (< .15s), but the generation of JSON using the TagsRepresenter took ~7s. In addition, when I ran the .to_json block, my memory ballooned to very high levels of usage, just as seen on the servers. 

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1255074/40962337-399359a0-6873-11e8-8c10-7be9146b895a.png">

**Comment by vaughanj10** [comment]
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/1255074/40996020-c9468a1c-68ce-11e8-9e4e-dec4bf407c7e.png">

This is from our testing in staging.affinity.works. 

In a group with 300 members and a database with tags, we are seeing response times from /memberships.json ranging between 700ms-1300ms. This passes our expectation to get all members page requests to under 2 seconds, and is an improvement from the prior state in which we observed response times >30sec under the same conditions.

QED
